=== reymac93/testtesttest/spotcableOrder_101.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- spotcable Order Schema Ver. 1.0.1 RELEASED:  8/12/03 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street" minOccurs="0"/>
				<xs:element ref="city" minOccurs="0"/>
				<xs:element ref="state" minOccurs="0"/>
				<xs:element ref="postalCode" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="optional" default="mailing"/>
			<xs:attribute name="country" type="xs:string" use="optional" default="US"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="advertiser">
		<xs:annotation>
			<xs:documentation>Often called client</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="ID" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="adx">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="document"/>
				<xs:element ref="campaign"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="affiliateSplit" default="0" nillable="1">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="breakoutMonth">
		<xs:annotation>
			<xs:documentation>yearMonth attrib. format: yyyy-mm</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="totals"/>
			</xs:sequence>
			<xs:attribute name="yearMonth" type="xs:gYearMonth" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="buyType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="weekly"/>
				<xs:enumeration value="daily"/>
				<xs:enumeration value=""/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="campaign">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" maxOccurs="unbounded"/>
				<xs:element ref="dateRange"/>
				<xs:element ref="company" maxOccurs="unbounded"/>
				<xs:element ref="advertiser"/>
				<xs:element ref="product"/>
				<xs:element ref="estimate" minOccurs="0"/>
				<xs:element ref="makeGoodPolicy" maxOccurs="unbounded"/>
				<xs:element ref="demo" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="buyType"/>
				<xs:element ref="populations" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="order" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="comment">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="company">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="office" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="contact" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ID" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Agency"/>
						<xs:enumeration value="Rep"/>
						<xs:enumeration value="CableSystem"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="role" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="contact">
		<xs:annotation>
			<xs:documentation>For NCC: role = AE or Assistant</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="firstName"/>
				<xs:element ref="lastName"/>
				<xs:element ref="email" maxOccurs="unbounded"/>
				<xs:element ref="phone" maxOccurs="unbounded"/>
				<xs:element ref="ID" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="role" type="xs:string" use="optional"/>
			<xs:attribute name="officeName" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="cost">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" type="xs:string" use="optional" default="US$"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="dateRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="startDate" type="xs:date">
					<xs:annotation>
						<xs:documentation>yyyy-mm-dd</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="endDate" type="xs:date">
					<xs:annotation>
						<xs:documentation>yyyy-mm-dd</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dayOfWeek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Monday" type="dayQuantity"/>
				<xs:element name="Tuesday" type="dayQuantity"/>
				<xs:element name="Wednesday" type="dayQuantity"/>
				<xs:element name="Thursday" type="dayQuantity"/>
				<xs:element name="Friday" type="dayQuantity"/>
				<xs:element name="Saturday" type="dayQuantity"/>
				<xs:element name="Sunday" type="dayQuantity"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="daypartCode" type="xs:string"/>
	<xs:element name="demo">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="demoNameComplexType">
					<xs:attribute name="demoRank" type="xs:int" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="demoValue">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="value" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:anySimpleType">
								<xs:attribute name="type" use="optional">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="Ratings"/>
											<xs:enumeration value="Impressions"/>
											<xs:enumeration value="CPP"/>
											<xs:enumeration value="CPM"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="demoRank" type="xs:string" use="required"/>
			<xs:attribute name="override" type="xs:boolean" use="optional" default="0"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="detailLine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="startTime" type="xs:time"/>
				<xs:element name="endTime" type="xs:time"/>
				<xs:element name="startDay">
					<xs:annotation>
						<xs:documentation>indicates start day of daypart</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="M"/>
							<xs:enumeration value="Tu"/>
							<xs:enumeration value="W"/>
							<xs:enumeration value="Th"/>
							<xs:enumeration value="F"/>
							<xs:enumeration value="Sa"/>
							<xs:enumeration value="Su"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="dayOfWeek"/>
				<xs:element name="length">
					<xs:annotation>
						<xs:documentation>PTnS</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:duration">
							<xs:minInclusive value="PT0S"/>
							<xs:maxInclusive value="PT3600S"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="daypartCode" minOccurs="0"/>
				<xs:element ref="program"/>
				<xs:element ref="comment"/>
				<xs:element ref="network" maxOccurs="unbounded"/>
				<xs:element ref="spotCost"/>
				<xs:element ref="demoValue" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="totals"/>
				<xs:element ref="spot" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="detailLineID" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="schemaVersion" type="xs:string" minOccurs="0"/>
				<xs:element ref="name"/>
				<xs:element name="date" type="xs:date"/>
				<xs:element name="mediaType">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Spotcable"/>
							<xs:enumeration value=""/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="documentType" type="xs:string"/>
				<xs:element name="documentCode" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="endTime" type="xs:time">
		<xs:annotation>
			<xs:documentation>hh:mm:ss</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="estimate">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="desc">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="ID"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="firstName">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ID" type="codeComplexType"/>
	<xs:element name="lastName">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="key">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string"/>
				<xs:element name="version" type="xs:string" minOccurs="0"/>
				<xs:element name="status" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ordered"/>
							<xs:enumeration value="confirmed"/>
							<xs:enumeration value="accepted"/>
							<xs:enumeration value="not accepted"/>
							<xs:enumeration value="cancelled"/>
							<xs:enumeration value="new"/>
							<xs:enumeration value="revised"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="subStatus" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="new"/>
							<xs:enumeration value="revised"/>
							<xs:enumeration value="cancelled"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="createDate" type="xs:date" minOccurs="0"/>
				<xs:element name="updateDate" type="xs:date" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="codeOwner" type="xs:string" use="required"/>
			<xs:attribute name="codeDescription" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="length">
		<xs:annotation>
			<xs:documentation>PTnS, where n=# of seconds</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:duration">
				<xs:minInclusive value="PT0S"/>
				<xs:maxInclusive value="PT3600S"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="makeGoodPolicy" type="codeComplexType"/>
	<xs:element name="market">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
			<xs:attribute name="nsi_id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255"/>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="network">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="0"/>
				<xs:element ref="ID" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="office">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="address"/>
				<xs:element ref="phone" maxOccurs="unbounded"/>
				<xs:element ref="ID" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="optional"/>
			<xs:attribute name="role" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" maxOccurs="unbounded"/>
				<xs:element ref="totals" minOccurs="0"/>
				<xs:element ref="market"/>
				<xs:element ref="survey" minOccurs="0"/>
				<xs:element ref="populations" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="comment"/>
				<xs:element ref="breakoutMonth" minOccurs="0" maxOccurs="12"/>
				<xs:element ref="systemOrder" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="fax"/>
								<xs:enumeration value="voice"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="country" type="xs:string" use="optional" default="US"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="populations">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="demoRank" type="xs:int" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="postalCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="5"/>
				<xs:maxLength value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="product">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="ID" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="program">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="specialCommission">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="spot">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="weekNumber" type="xs:nonNegativeInteger"/>
				<xs:element name="quantity" type="xs:nonNegativeInteger"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="spots" type="xs:nonNegativeInteger"/>
	<xs:element name="spotCost">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="currency" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="startTime" type="xs:time">
		<xs:annotation>
			<xs:documentation>hh:mm:ss</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="state">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="code" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:length value="2"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="street" type="xs:string"/>
	<xs:element name="survey">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ratingService" type="xs:string"/>
				<xs:element name="geography" type="xs:string"/>
				<xs:element name="shareBook" type="xs:string"/>
				<xs:element name="PUTBook" type="xs:string"/>
				<xs:element name="profile" type="xs:string"/>
				<xs:element name="comment" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="codeOwner" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element name="syscode" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="systemOrder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" maxOccurs="unbounded"/>
				<xs:element ref="comment"/>
				<xs:element ref="system" maxOccurs="unbounded"/>
				<xs:element ref="affiliateSplit"/>
				<xs:element ref="specialCommission" minOccurs="0"/>
				<xs:element ref="populations" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="totals"/>
				<xs:element ref="weeks"/>
				<xs:element ref="breakoutMonth" minOccurs="0" maxOccurs="12"/>
				<xs:element ref="detailLine" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="totals">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cost"/>
				<xs:element ref="spots"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="week">
		<xs:complexType>
			<xs:attribute name="number" use="required">
				<xs:simpleType>
					<xs:restriction base="weeksNumberSimpleType"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="startDate" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="weeks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="week" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="count" use="required">
				<xs:simpleType>
					<xs:restriction base="weeksNumberSimpleType"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="codeComplexType">
		<xs:sequence>
			<xs:element ref="comment" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="code">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="codeOwner" type="xs:string" use="optional"/>
							<xs:attribute name="codeDescription" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="dayQuantity">
		<xs:annotation>
			<xs:documentation>holds a number, "Y" for unspecified, or "N" for invalid</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]+)|(Y)|(N)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="demoNameComplexType">
		<xs:annotation>
			<xs:documentation>custom type for demo elements</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="group">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Households">
							<xs:annotation>
								<xs:documentation>HH - Households
</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="Adults"/>
						<xs:enumeration value="Men"/>
						<xs:enumeration value="Women"/>
						<xs:enumeration value="Teens"/>
						<xs:enumeration value="Children"/>
						<xs:enumeration value="Persons"/>
						<xs:enumeration value="Homes"/>
						<xs:enumeration value="Total"/>
						<xs:enumeration value="WWomen"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ageFrom" type="xs:integer"/>
			<xs:element name="ageTo" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="weeksNumberSimpleType">
		<xs:annotation>
			<xs:documentation>custom type for attributes describing weeks in a year (broadcast), only allowed 1 to 53</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="53"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== reymac93/testtesttest/ncc.xml
<?xml version="1.0" encoding="utf-8"?>
<adx xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.spotcable.com/schema/spotcableOrder_101.xsd">
  <document>
    <schemaVersion>1.0.1</schemaVersion>
    <name>SpotCable Order XML</name>
    <date>2010-06-07</date>
    <mediaType>Spotcable</mediaType>
    <documentType>Order</documentType>
    <documentCode>1</documentCode>
  </document>
  <campaign>
    <key codeOwner="NCC">
      <id>61135360</id>
    </key>
    <dateRange>
      <startDate>2009-06-29</startDate>
      <endDate>2009-09-27</endDate>
    </dateRange>
    <company type="Rep" role="">
      <name>NCC</name>
      <office>
        <name><![CDATA[NCC - Detroit]]></name>
        <address country="US" type="mailing">
          <street><![CDATA[1000 Town Center Suite 480]]></street>
          <city><![CDATA[Southfield]]></city>
          <state code="MI" />
          <postalCode>48075</postalCode>
        </address>
        <phone country="US" type="voice">(248) 728-0800</phone>
        <phone country="US" type="fax">(248) 728-0801</phone>
        <ID>
          <code codeOwner="NCC">7</code>
        </ID>
      </office>
      <contact role="AE">
        <firstName><![CDATA[Linda]]></firstName>
        <lastName><![CDATA[Kahan]]></lastName>
        <email><![CDATA[Linda_Kahan@spotcable.com]]></email>
        <phone country="US" type="voice">(248) 728-0800</phone>
        <phone country="US" type="fax">(248) 728-0801</phone>
        <ID>
          <code codeOwner="NCC">64</code>
        </ID>
      </contact>
      <ID>
        <code codeDescription="" codeOwner="NCC">NCC</code>
      </ID>
    </company>
    <company type="Agency" role="">
      <name><![CDATA[GroupM Motion]]></name>
      <office>
        <name><![CDATA[GroupM Motion]]></name>
        <address country="US" type="mailing">
          <street><![CDATA[498 Seventh Avenue]]></street>
          <city><![CDATA[New York]]></city>
          <state code="NY" />
          <postalCode>10018</postalCode>
        </address>
        <phone country="US" type="voice" />
      </office>
      <ID>
        <code codeOwner="NCC">707166</code>
      </ID>
    </company>
    <advertiser>
      <name><![CDATA[Ford - Cinn. District Ford Dlr.]]></name>
      <ID>
        <comment />
        <code codeDescription="" codeOwner="NCC">56942</code>
      </ID>
      <ID>
        <comment />
        <code codeDescription="" codeOwner="Agency">ZCD</code>
      </ID>
    </advertiser>
    <product>
      <name><![CDATA[ ]]></name>
      <ID>
        <comment />
        <code codeDescription="" codeOwner="Agency"><![CDATA[CAR]]></code>
      </ID>
    </product>
    <estimate>
      <desc><![CDATA[Lexington-Fayette - 10360449]]></desc>
      <ID>
        <code codeDescription="" codeOwner="Agency">011</code>
      </ID>
    </estimate>
    <makeGoodPolicy>
      <code codeDescription="Approval Required" codeOwner="NCC">A</code>
    </makeGoodPolicy>
    <demo demoRank="1">
      <group>Adults</group>
      <ageFrom>25</ageFrom>
      <ageTo>54</ageTo>
    </demo>
    <buyType>weekly</buyType>
    <populations demoRank="1">15984</populations>
    <order>
      <key codeOwner="NCC">
        <id>61338850</id>
        <status>confirmed</status>
        <subStatus>new</subStatus>
        <updateDate>2009-02-12</updateDate>
      </key>
      <totals>
        <cost currency="USD">4125</cost>
        <spots>752</spots>
      </totals>
      <market nsi_id="141">
        <name><![CDATA[Lexington-Fayette]]></name>
      </market>
      <survey>
        <ratingService />
        <geography>Zone</geography>
        <shareBook />
        <PUTBook />
        <profile />
        <comment codeOwner="NCC"><![CDATA[May08 ST Nielsen CBL #]]></comment>
      </survey>
      <populations demoRank="1">15984</populations>
      <comment><![CDATA[ ]]></comment>
      <breakoutMonth yearMonth="2009-01">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-02">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-03">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-04">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-05">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-06">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-07">
        <totals>
          <cost currency="USD">1309</cost>
          <spots>238</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-08">
        <totals>
          <cost currency="USD">1611</cost>
          <spots>294</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-09">
        <totals>
          <cost currency="USD">1205</cost>
          <spots>220</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-10">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-11">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <breakoutMonth yearMonth="2009-12">
        <totals>
          <cost currency="USD">0</cost>
          <spots>0</spots>
        </totals>
      </breakoutMonth>
      <systemOrder>
        <key codeOwner="NCC">
          <id>1076753</id>
          <version>1</version>
          <status>accepted</status>
          <subStatus>new</subStatus>
          <updateDate>2009-02-12</updateDate>
        </key>
        <comment><![CDATA[New Order. Please confirm within 48 hrs.]]></comment>
        <system>
          <name><![CDATA[Ad Systems/Hindman, KY]]></name>
          <syscode>9307 </syscode>
        </system>
        <affiliateSplit>0</affiliateSplit>
        <populations demoRank="1">15283</populations>
        <totals>
          <cost currency="USD">2190</cost>
          <spots>365</spots>
        </totals>
        <weeks count="13">
          <week number="1" startDate="2009-06-29" />
          <week number="2" startDate="2009-07-06" />
          <week number="3" startDate="2009-07-13" />
          <week number="4" startDate="2009-07-20" />
          <week number="5" startDate="2009-07-27" />
          <week number="6" startDate="2009-08-03" />
          <week number="7" startDate="2009-08-10" />
          <week number="8" startDate="2009-08-17" />
          <week number="9" startDate="2009-08-24" />
          <week number="10" startDate="2009-08-31" />
          <week number="11" startDate="2009-09-07" />
          <week number="12" startDate="2009-09-14" />
          <week number="13" startDate="2009-09-21" />
        </weeks>
        <breakoutMonth yearMonth="2009-01">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-02">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-03">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-04">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-05">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-06">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-07">
          <totals>
            <cost currency="USD">714</cost>
            <spots>119</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-08">
          <totals>
            <cost currency="USD">846</cost>
            <spots>141</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-09">
          <totals>
            <cost currency="USD">630</cost>
            <spots>105</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-10">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-11">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <breakoutMonth yearMonth="2009-12">
          <totals>
            <cost currency="USD">0</cost>
            <spots>0</spots>
          </totals>
        </breakoutMonth>
        <detailLine detailLineID="25244648">
          <startTime>18:00:00</startTime>
          <endTime>00:00:00</endTime>
          <startDay>M</startDay>
          <dayOfWeek>
            <Monday>Y</Monday>
            <Tuesday>Y</Tuesday>
            <Wednesday>Y</Wednesday>
            <Thursday>Y</Thursday>
            <Friday>Y</Friday>
            <Saturday>0</Saturday>
            <Sunday>0</Sunday>
          </dayOfWeek>
          <length>PT30S</length>
